## Array indexing and slicing in numpy

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic slicing: ", arr[3:8])
print("Slicing with step: ", arr[1:8:2])
print("Inverse slicing: ", arr[-3])

Basic slicing:  [4 5 6 7 8]
Slicing with step:  [2 4 6 8]
Inverse slicing:  8


In [4]:
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6],
                   [7, 8, 9]
                ])
print("Specific element: ", arr_2d[1,2])
print("Entire row: ", arr_2d[1])
print("Entire column: ", arr_2d[:, 2])

Specific element:  6
Entire row:  [4 5 6]
Entire column:  [3 6 9]


## Sorting

In [5]:
unsorted = np.array([1,5,2,9,6,8,1,4,3,5])
print("Sorting array: ", np.sort(unsorted))

arr_2d_unsorted = np.array([[21,53], [63,45],[98,85]])
print("Sorting 2d array by column: ", np.sort(arr_2d_unsorted,axis=0))
print("Sorting 2d array by row: ", np.sort(arr_2d_unsorted,axis=1))


Sorting array:  [1 1 2 3 4 5 5 6 8 9]
Sorting 2d array by column:  [[21 45]
 [63 53]
 [98 85]]
Sorting 2d array by row:  [[21 53]
 [45 63]
 [85 98]]


## Filter

In [7]:
numbers = np.array(range(1, 11))
even_numbers = numbers[numbers % 2 == 0]
print("Even numbers: ", even_numbers)

Even numbers:  [ 2  4  6  8 10]


## Filter with mask

In [11]:
mask = numbers > 5
print("Numbers reater than 5: ", numbers[mask])

Numbers reater than 5:  [ 6  7  8  9 10]


## Fancy indexing vs where

In [19]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print("Numbers where greater than 5: ", numbers[where_result])

condition_array = np.where(numbers > 5, numbers * 2, numbers * 3)
print(condition_array)

[1 3 5]
Numbers where greater than 5:  [ 6  7  8  9 10]
[ 3  6  9 12 15 12 14 16 18 20]


## Array adding and removing

In [23]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


## Array compatibility

In [28]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("Compatibilty shape: ", a.shape == b.shape)

original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])
with_new_row = np.vstack((original, new_row))
print("With new row: ", with_new_row)
new_col = np.array([[7],[8]])
with_new_col = np.hstack((original, new_col))
print("With new col: ", with_new_col)

Compatibilty shape:  True
With new row:  [[1 2]
 [3 4]
 [5 6]]
With new col:  [[1 2 7]
 [3 4 8]]


## Deletion

In [32]:
num = np.array([[1,2,3],[4,5,6]])
deleted = np.delete(num, 4)
print(deleted)

[1 2 3 4 6]
